// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Rk6BaJizahPRQxmecL9wB1U-SXmtZRE',
    appId: '1:917244590963:web:d9e7ac85e208e15d462306',
    messagingSenderId: '917244590963',
    projectId: 'todo-app-fa619',
    authDomain: 'todo-app-fa619.firebaseapp.com',
    storageBucket: 'todo-app-fa619.firebasestorage.app',
    measurementId: 'G-YPG9R0PQZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGM3wSqvCP7vaj2mG6GGDx4WleHyjTqe0',
    appId: '1:917244590963:android:a7e516bf8711e845462306',
    messagingSenderId: '917244590963',
    projectId: 'todo-app-fa619',
    storageBucket: 'todo-app-fa619.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0k93F0QGcyAjFs04lZX9QRWQ3PYHSajE',
    appId: '1:917244590963:ios:8dbd008060692df4462306',
    messagingSenderId: '917244590963',
    projectId: 'todo-app-fa619',
    storageBucket: 'todo-app-fa619.firebasestorage.app',
    iosBundleId: 'com.example.todoRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0k93F0QGcyAjFs04lZX9QRWQ3PYHSajE',
    appId: '1:917244590963:ios:8dbd008060692df4462306',
    messagingSenderId: '917244590963',
    projectId: 'todo-app-fa619',
    storageBucket: 'todo-app-fa619.firebasestorage.app',
    iosBundleId: 'com.example.todoRiverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1Rk6BaJizahPRQxmecL9wB1U-SXmtZRE',
    appId: '1:917244590963:web:865158a457cf7910462306',
    messagingSenderId: '917244590963',
    projectId: 'todo-app-fa619',
    authDomain: 'todo-app-fa619.firebaseapp.com',
    storageBucket: 'todo-app-fa619.firebasestorage.app',
    measurementId: 'G-8H9LH7WZYR',
  );
}
